/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import model.WumpusWorld;
import model.observations.Scenario;

/**
 *
 * @author silmathoron
 */
public class WumpusWorldPanel extends javax.swing.JPanel {

    private Scenario scenario;
    private WumpusWorld wumpusWorld;
    private int instant = 0;
    private int cellHeight = 20;
    private int cellWidth = 20;

    /**
     * Creates new form WumpusWorldPanel
     */
    public WumpusWorldPanel() {
        initComponents();
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2 = (Graphics2D) g;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

        g2.drawString("It's a Wumpus World", 20, 20);
        if (scenario != null && wumpusWorld != null) {
            paintGrid(g2);
            //paintObjects(g2);
        }
    }

    public void setScenario(Scenario scenario) {
        this.scenario = scenario;
    }

    public void setWumpusWorld(WumpusWorld wumpusWorld) {
        this.wumpusWorld = wumpusWorld;
    }

    public void setInstant(int instant) {
        this.instant = instant;
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void paintGrid(Graphics2D g2) {
        for (int i = 0; i < wumpusWorld.getHeight(); i++) {
            for (int j = 0; j < wumpusWorld.getWidth(); j++) {
                g2.drawRect(j * cellWidth, i * cellHeight, WIDTH, HEIGHT);
            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
