package gui;

import javax.swing.DefaultBoundedRangeModel;
import model.WumpusWorld;
import model.observations.Scenario;

/**
 *
 * @author Paul Givel and Guillaume Hartenstein
 */
public class WumpusWorldFrame extends javax.swing.JFrame {
    private Scenario scenario;
    private WumpusWorld wumpusWorld;
    
    /**
     * Creates new form WumpusWorldFrame
     */
    public WumpusWorldFrame(Scenario scenario, WumpusWorld wumpusWorld) {
        this.wumpusWorld = wumpusWorld;
        this.scenario = scenario;
        initComponents();
        wumpusWorldPanel1.setWumpusWorld(wumpusWorld);
        wumpusWorldPanel1.setScenario(scenario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInstant = new javax.swing.JPanel();
        wumpusWorldPanel1 = new gui.WumpusWorldPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelInstant.setLayout(new java.awt.BorderLayout());

        sliderInstant.setMaximum(0);
        sliderInstant.setPaintLabels(true);
        sliderInstant.setPaintTicks(true);
        sliderInstant.setSnapToTicks(true);
        sliderInstant.setModel(new DefaultBoundedRangeModel(
            0,
            0,
            0,
            scenario.size()-1)
    );
    sliderInstant.addChangeListener(new javax.swing.event.ChangeListener() {
        public void stateChanged(javax.swing.event.ChangeEvent evt) {
            sliderInstantStateChanged(evt);
        }
    });
    panelInstant.add(sliderInstant, java.awt.BorderLayout.CENTER);

    getContentPane().add(panelInstant, java.awt.BorderLayout.SOUTH);

    javax.swing.GroupLayout wumpusWorldPanel1Layout = new javax.swing.GroupLayout(wumpusWorldPanel1);
    wumpusWorldPanel1.setLayout(wumpusWorldPanel1Layout);
    wumpusWorldPanel1Layout.setHorizontalGroup(
        wumpusWorldPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 400, Short.MAX_VALUE)
    );
    wumpusWorldPanel1Layout.setVerticalGroup(
        wumpusWorldPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 269, Short.MAX_VALUE)
    );

    getContentPane().add(wumpusWorldPanel1, java.awt.BorderLayout.CENTER);

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sliderInstantStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderInstantStateChanged
        wumpusWorldPanel1.setInstant(sliderInstant.getValue());
    }//GEN-LAST:event_sliderInstantStateChanged
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelInstant;
    private final javax.swing.JSlider sliderInstant = new javax.swing.JSlider();
    private gui.WumpusWorldPanel wumpusWorldPanel1;
    // End of variables declaration//GEN-END:variables
}
