/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.solver;

import ilog.concert.IloException;
import java.awt.CardLayout;
import java.util.List;
import javax.swing.JOptionPane;
import model.Trajectory;
import solver.BacktrackSolver;

/**
 *
 * @author Paul Givel and Guillaume Hartenstein
 */
public class BacktrackSolverResults extends javax.swing.JFrame {
    private Integer _solution;
    private final List<Trajectory> trajectories;

    /**
     * Creates new form BacktrackSolverResults
     * @param solver
     * @throws ilog.concert.IloException
     */
    public BacktrackSolverResults(BacktrackSolver solver) throws IloException {
        trajectories = solver.solve();
        _solution = 0;
        
        initComponents();
        
        for (Trajectory trajectory : trajectories) {
            panelTrajectoryGraph.add(_solution.toString(), new TrajectoryGraphPanel(trajectory, solver.getInstantCount()));
        }
        
        btnNext.setEnabled(!trajectories.isEmpty());
        btnPrevious.setEnabled(!trajectories.isEmpty());
        
        super.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        panelGraphics = new javax.swing.JPanel();
        panelNav = new javax.swing.JPanel();
        btnPrevious = new javax.swing.JButton();
        lblNavInfo = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();
        panelTrajectoryGraph = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        menuSave = new javax.swing.JMenu();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Backtrack algorithm results");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        panelGraphics.setLayout(new java.awt.BorderLayout());

        panelNav.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 5));

        btnPrevious.setText("Previous");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });
        panelNav.add(btnPrevious);

        lblNavInfo.setText("Solution  "
            +(trajectories.isEmpty() ? _solution : _solution+1)
            +" / "
            +trajectories.size());
        panelNav.add(lblNavInfo);

        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        panelNav.add(btnNext);

        panelGraphics.add(panelNav, java.awt.BorderLayout.NORTH);

        panelTrajectoryGraph.setPreferredSize(new java.awt.Dimension(500, 400));
        panelTrajectoryGraph.setLayout(new java.awt.CardLayout());
        panelGraphics.add(panelTrajectoryGraph, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelGraphics, java.awt.BorderLayout.CENTER);

        menuSave.setText("Save");
        menuBar.add(menuSave);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        _solution--;
        if (_solution < 0) {
            _solution = trajectories.size()-1;
        }
        setNavInfo();
        ((CardLayout)panelTrajectoryGraph.getLayout()).previous(panelTrajectoryGraph);
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        _solution++;
        _solution %= trajectories.size();
        setNavInfo();
        ((CardLayout)panelTrajectoryGraph.getLayout()).next(panelTrajectoryGraph);
    }//GEN-LAST:event_btnNextActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        JOptionPane.showMessageDialog(this, 
                "The solving terminated successfully, finding "+ trajectories.size() +" solutions.",
                "Solver information",
                JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_formWindowOpened

    private void setNavInfo() {
        lblNavInfo.setText("Solution  "+(_solution+1)+" / "+trajectories.size());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel lblNavInfo;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuSave;
    private javax.swing.JPanel panelGraphics;
    private javax.swing.JPanel panelNav;
    private javax.swing.JPanel panelTrajectoryGraph;
    // End of variables declaration//GEN-END:variables
}
