/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.solver;

import gui.general.GeneralUI;
import model.World;
import model.observations.Scenario;

/**
 *
 * @author Paul Givel and Guillaume Hartenstein
 */
public class SolverChooser extends javax.swing.JDialog {

    private final World world;
    private final Scenario scenario;

    /**
     * Creates new form SolverUI
     * @param world The world to operate on
     * @param scenario The scenario to operate on
     * @param parent The calling UI
     */ 
    public SolverChooser(World world, Scenario scenario, GeneralUI parent) {
        super(parent);
        this.world = world;
        this.scenario = scenario;
        initComponents();
        super.setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelChoose = new javax.swing.JPanel();
        lblAlgo = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        scrollAreaInfo = new javax.swing.JScrollPane();
        areaInfo = new javax.swing.JTextArea();
        panelButtons = new javax.swing.JPanel();
        btnStart = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Solver chooser");

        lblAlgo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblAlgo.setText("Solving algorithm: ");
        panelChoose.add(lblAlgo);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setPreferredSize(new java.awt.Dimension(150, 20));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        panelChoose.add(jComboBox1);

        getContentPane().add(panelChoose, java.awt.BorderLayout.NORTH);

        areaInfo.setEditable(false);
        areaInfo.setColumns(20);
        areaInfo.setLineWrap(true);
        areaInfo.setRows(5);
        areaInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Algorithm description", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        areaInfo.setOpaque(false);
        scrollAreaInfo.setViewportView(areaInfo);

        getContentPane().add(scrollAreaInfo, java.awt.BorderLayout.CENTER);

        btnStart.setText("Start solving");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });
        panelButtons.add(btnStart);

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        panelButtons.add(btnCancel);

        getContentPane().add(panelButtons, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStartActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaInfo;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnStart;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel lblAlgo;
    private javax.swing.JPanel panelButtons;
    private javax.swing.JPanel panelChoose;
    private javax.swing.JScrollPane scrollAreaInfo;
    // End of variables declaration//GEN-END:variables
}
