/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.general;

import java.util.List;
import model.Condition;
import model.ObjectProperty;
import model.SysObject;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import model.exceptions.DuplicateElementException;


/**
 *
 * @author Paul Givel and Guillaume Hartenstein
 */
public class AddConditionDialog extends javax.swing.JDialog {
    private SysObject[] objects;
    private List<Condition> conditions;
    
    private SysObject _object;
    private ObjectProperty _property;
    private String _propValue;
    
    /**
     * Creates new form AddConditionDialog
     * @param parent
     * @param objects
     * @param conditions
     */
    public AddConditionDialog(java.awt.Frame parent, List<SysObject> objects, List<Condition> conditions) {
        super(parent, true);
        
        this.objects = new SysObject[objects.size()];
        this.conditions = conditions;
        
        for (int i = 0; i < this.objects.length; i++) {
            this.objects[i] = objects.get(i);
        }
        
        initComponents();
        
        cbObjectItemStateChanged(null);
        cbPropItemStateChanged(null);
        
        super.setLocationRelativeTo(parent);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputPanel = new javax.swing.JPanel();
        lblObject = new javax.swing.JLabel();
        cbObject = new javax.swing.JComboBox<>();
        lblProp = new javax.swing.JLabel();
        lblPopValue = new javax.swing.JLabel();
        cbProp = new javax.swing.JComboBox<>();
        cbPropValue = new javax.swing.JComboBox<>();
        buttonsPanel = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Adding a condition");
        setResizable(false);

        lblObject.setText("Object:");

        cbObject.setModel(new DefaultComboBoxModel<SysObject>(objects));
        cbObject.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbObjectItemStateChanged(evt);
            }
        });

        lblProp.setText("Property:");

        lblPopValue.setText("Value:");

        cbProp.setModel(new DefaultComboBoxModel<ObjectProperty>());
        cbProp.setEnabled(false);
        cbProp.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbPropItemStateChanged(evt);
            }
        });

        cbPropValue.setModel(new DefaultComboBoxModel<String>());
        cbPropValue.setEnabled(false);
        cbPropValue.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbPropValueItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout inputPanelLayout = new javax.swing.GroupLayout(inputPanel);
        inputPanel.setLayout(inputPanelLayout);
        inputPanelLayout.setHorizontalGroup(
            inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblObject, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProp)
                    .addComponent(lblPopValue, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbObject, javax.swing.GroupLayout.Alignment.TRAILING, 0, 129, Short.MAX_VALUE)
                    .addComponent(cbProp, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbPropValue, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        inputPanelLayout.setVerticalGroup(
            inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblObject)
                    .addComponent(cbObject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProp)
                    .addComponent(cbProp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPopValue)
                    .addComponent(cbPropValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(inputPanel, java.awt.BorderLayout.CENTER);

        btnAdd.setText("Add");
        btnAdd.setEnabled(false);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        buttonsPanel.add(btnAdd);

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        buttonsPanel.add(btnCancel);

        getContentPane().add(buttonsPanel, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbObjectItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbObjectItemStateChanged
        _object = (SysObject) cbObject.getSelectedItem();
        
        try {
            List<ObjectProperty> objectProps = _object.getProperties();
            if(objectProps.isEmpty())
                throw new NullPointerException();
            ObjectProperty[] properties = new ObjectProperty[objectProps.size()];
            for (int i = 0; i < properties.length; i++) {
                properties[i] = objectProps.get(i);
            }
            cbProp.setModel(new DefaultComboBoxModel<>(properties));
            cbProp.setEnabled(true);
        } catch (NullPointerException e) {
            cbProp.setModel(new DefaultComboBoxModel<ObjectProperty>());
            cbProp.setEnabled(false);
        } finally {
            cbPropItemStateChanged(null);
        }
    }//GEN-LAST:event_cbObjectItemStateChanged

    private void cbPropItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbPropItemStateChanged
        _property = (ObjectProperty) cbProp.getSelectedItem();
        
        try {
            List<String> propValues = _property.getPossibleValues();
            if(propValues.isEmpty())
                throw new NullPointerException();
            String[] values = new String[propValues.size()];
            for (int i = 0; i < values.length; i++) {
                values[i] = propValues.get(i);
            }
            cbPropValue.setModel(new DefaultComboBoxModel<>(values));
            cbPropValue.setEnabled(true);
            btnAdd.setEnabled(true);
        } catch (NullPointerException e) {
            cbPropValue.setModel(new DefaultComboBoxModel<String>());
            cbPropValue.setEnabled(false);
            btnAdd.setEnabled(false);
        } finally {
            cbPropValueItemStateChanged(null);
        }
    }//GEN-LAST:event_cbPropItemStateChanged

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try {
            conditions.add(new Condition(_object, _property.getName(), _propValue));
            ((GeneralUI)getParent()).warnSave();
            dispose();
        } catch (DuplicateElementException e) {
            JOptionPane.showMessageDialog(this,
                    "This condition already exists",
                    "Cannot add condition", 
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void cbPropValueItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbPropValueItemStateChanged
        _propValue = (String) cbPropValue.getSelectedItem();
    }//GEN-LAST:event_cbPropValueItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JComboBox<SysObject> cbObject;
    private javax.swing.JComboBox<ObjectProperty> cbProp;
    private javax.swing.JComboBox<String> cbPropValue;
    private javax.swing.JPanel inputPanel;
    private javax.swing.JLabel lblObject;
    private javax.swing.JLabel lblPopValue;
    private javax.swing.JLabel lblProp;
    // End of variables declaration//GEN-END:variables
}
