/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.wumpus;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import javax.swing.JLabel;

/**
 *
 * @author silmathoron
 */
public class CellPanel extends javax.swing.JPanel {

    Graphics g;
    WumpusWorldPanel wumpusWorldPanel;
    int mainX;
    int mainY;

    int mainFontSize = 60;
    int altFontSize = 20;

    /**
     * Creates new form CellPanel
     *
     * @param wumpusWorldPanel
     * @param mainX
     * @param mainY
     * @param letter
     */
    public CellPanel(WumpusWorldPanel wumpusWorldPanel, int mainX, int mainY, String letter) {
        this.wumpusWorldPanel = wumpusWorldPanel;
        this.mainX = mainX;
        this.mainY = mainY;
        initComponents();
        mainLabel.setFont(new Font(Font.MONOSPACED, Font.PLAIN, mainFontSize));
        mainLabel.setForeground(Color.gray);
        mainLabel.setText(letter);
    }



    public void setAlt(int position, Color color1, Color color2, String letter1, String letter2, boolean activated) {
        JLabel altlabel;
        switch (position) {
            case 1:
                altlabel = altLabel1;
                break;
            case 2:
                altlabel = altLabel2;
                break;
            case 3:
                altlabel = altLabel3;
                break;
            case 4:
                altlabel = altLabel4;
                break;
            default:
                altlabel = new JLabel();

        }
        altlabel.setFont(new Font(Font.MONOSPACED, Font.PLAIN, altFontSize));
        if (activated) {
            altlabel.setForeground(color1);
            altlabel.setText(letter1);
        } else {
            altlabel.setForeground(color2);
            altlabel.setText(letter2);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainLabel = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        altsPanel = new javax.swing.JPanel();
        altLabel1 = new javax.swing.JLabel();
        altLabel2 = new javax.swing.JLabel();
        altLabel3 = new javax.swing.JLabel();
        altLabel4 = new javax.swing.JLabel();

        mainLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.lightGray));
        setPreferredSize(new java.awt.Dimension(200, 200));

        altsPanel.setPreferredSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout altsPanelLayout = new javax.swing.GroupLayout(altsPanel);
        altsPanel.setLayout(altsPanelLayout);
        altsPanelLayout.setHorizontalGroup(
            altsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(altsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(altsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(altLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(altLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 6, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(altsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(altLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(altLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        altsPanelLayout.setVerticalGroup(
            altsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(altsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(altsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(altLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(altLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 14, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(altsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(altLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(altLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLayeredPane1.setLayer(altsPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 198, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(altsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 198, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(altsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel altLabel1;
    private javax.swing.JLabel altLabel2;
    private javax.swing.JLabel altLabel3;
    private javax.swing.JLabel altLabel4;
    private javax.swing.JPanel altsPanel;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel mainLabel;
    // End of variables declaration//GEN-END:variables
}
