/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.wumpus;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.FontMetrics;
import java.awt.Graphics;
import java.awt.Rectangle;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author silmathoron
 */
public class CellPanel extends javax.swing.JPanel {

    Graphics g;
    WumpusWorldPanel wumpusWorldPanel;
    int mainX;
    int mainY;

    int mainFontSize = 60;
    int altFontSize = 20;

    /**
     * Creates new form CellPanel
     *
     * @param wumpusWorldPanel
     * @param mainX
     * @param mainY
     * @param letter
     */
    public CellPanel(WumpusWorldPanel wumpusWorldPanel, int mainX, int mainY, String letter) {
        this.wumpusWorldPanel = wumpusWorldPanel;
        this.mainX = mainX;
        this.mainY = mainY;
        initComponents();
        mainLabel.setFont(new Font(Font.MONOSPACED, Font.PLAIN, mainFontSize));
        mainLabel.setForeground(Color.gray);
        mainLabel.setText(letter);
    }



    public void setAlt(int position, Color color1, Color color2, String letter1, String letter2, boolean activated) {
        JLabel altlabel;
        switch (position) {
            case 1:
                altlabel = altLabel1;
                break;
            case 2:
                altlabel = altLabel2;
                break;
            case 3:
                altlabel = altLabel3;
                break;
            case 4:
                altlabel = altLabel4;
                break;
            default:
                altlabel = new JLabel();

        }
        altlabel.setFont(new Font(Font.MONOSPACED, Font.PLAIN, altFontSize));
        if (activated) {
            altlabel.setForeground(color1);
            altlabel.setText(letter1);
        } else {
            altlabel.setForeground(color2);
            altlabel.setText(letter2);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        altLabel1 = new javax.swing.JLabel();
        altLabel2 = new javax.swing.JLabel();
        altLabel3 = new javax.swing.JLabel();
        altLabel4 = new javax.swing.JLabel();
        mainLabel = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(70, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(altLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addComponent(altLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(mainLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(altLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(altLabel4)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(altLabel1)
                    .addComponent(altLabel2))
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mainLabel)
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(altLabel3)
                    .addComponent(altLabel4))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel altLabel1;
    private javax.swing.JLabel altLabel2;
    private javax.swing.JLabel altLabel3;
    private javax.swing.JLabel altLabel4;
    private javax.swing.JLabel mainLabel;
    // End of variables declaration//GEN-END:variables
}
